client/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from client.views import *

urlpatterns = [
	path('', IndexView.as_view(), name='client.index'),
	path('pages/<slug:page_slug>/', PageSingleView.as_view(), name='client.page.single'),

	# Calculator URL'S
	path('calculator/', CalculatorIndexView.as_view(), name='client.calculator.index'),

	path('calculator/life/', CalculatorLifeView.as_view(), name='client.calculator.life'),
	path('calculator/life-results/', CalculatorLifeResultView.as_view(), name='client.calculator.life_result'),
	path('calculator/<int:insurance_id>/life-request/', CalculatorLifeRequestView.as_view(),
		 name='client.calculator.life_request'),

	path('calculator/medical/', CalculatorMedicalView.as_view(), name='client.calculator.medical'),
	path('calculator/medical-results/', CalculatorMedicalResultView.as_view(), name='client.calculator.medical_result'),
	path('calculator/<int:insurance_id>/medical-request/', CalculatorMedicalRequestView.as_view(),
		 name='client.calculator.medical_request'),

	path('calculator/home/', CalculatorHomeView.as_view(), name='client.calculator.home'),
	path('calculator/home-results/', CalculatorHomeResultView.as_view(), name='client.calculator.home_result'),
	path('calculator/<int:insurance_id>/home-request/', CalculatorHomeRequestView.as_view(),
		 name='client.calculator.home_request'),

	#client/calculator/calculator_vehicle.htm
	path('calculator/vehicle/', CalculatorVehicleView.as_view(), name='client.calculator.vehicle'),
	path('calculator/vehicle-results/', CalculatorVehicleResultView.as_view(), name='client.calculator.vehicle_result'),
	path('calculator/vehicle-client-info/', CalculatorVehicleClientInfoView.as_view(), name='client.calculator.vehicle_client_info'),
	path('calculator/vehicle-client-info-result/', CalculatorVehicleClientInfoResultView.as_view(), name='client.calculator.vehicle_client_info_result'),
	
	path('calculator/vehicle-info/', CalculatorVehicleInfoView.as_view(), name='client.calculator.vehicle_info'),
	path('calculator/vehicle-info-result/', CalculatorVehicleInfoResultView.as_view(), name='client.calculator.vehicle_info_result'),
	path('calculator/vehicle-sugese-info/', CalculatorVehicleSugeseInfoView.as_view(), name='client.calculator.vehicle_sugese_info'),
	#path('calculator/vehicle-sugese-info-result/', CalculatorVehicleSugeseInfoResultView.as_view(), name='client.calculator.calculator_payment_oceanica'),

	path('calculator/get-brand-model-by-plate/', GetBrandModelbyPlate.as_view(), name='client.calculator.get_brand_model_by_plate'),
	
	#payments
	#CalculatorPaymentTypeView
	path('calculator/payments-type/',CalculatorPaymentTypeView.as_view(), name='client.calculator.payments_type'),
	#path('calculator/payments-Oceanica/',CalculatorOceanicaPaymentsView.as_view(), name='client.calculator.payment_oceanica'),
	path('calculator/payments-results/',CalculatorPaymentResults.as_view(), name='client.calculator.payment_result'),
	path('calculator/payments-simulation/',CalculatorPaymentSimulation.as_view(), name='client.calculator.payment_simulation'),
	path('calculator/payments-success/',CalculatorPaymentSuccess.as_view(), name='client.calculator.payment_success'),
	path('calculator/payments-confirm/',CalculatorPaymentConfirmView.as_view(), name='client.calculator.payment_confirm'),


	path('calculator/<int:insurance_id>/vehicle-request/', CalculatorVehicleRequestView.as_view(),
		 name='client.calculator.vehicle_request'),

	path('calculator/sent-request/', CalculatorSentRequestView.as_view(), name='client.calculator.sent_request'),

	# Contact Form URL'S
	path('contact-form/', ContactFormSendView.as_view(), name='client.contact_form'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insurance/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from insurance.views import *

urlpatterns = [
	path('', PostListView.as_view(), name='insurance.index'),

	# Posts URL'S
	path('post/', PostListView.as_view(), name='insurance.post.list'),
	path('post/add/', PostAddView.as_view(), name='insurance.post.add'),
	path('post/<int:pk>/edit/', PostEditView.as_view(), name='insurance.post.edit'),
	path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='insurance.post.delete'),
	path('post/sort/', PostSortView.as_view(), name='insurance.post.sort'),

	# Post Image URL'S
	path('post-image/<int:post_id>/add/', PostImageAddView.as_view(), name='insurance.post_image.add'),
	path('post-image/<int:post_image_id>/delete/', PostImageDeleteView.as_view(), name='insurance.post_image.delete'),

	# Section Home URL'S
	path('section-home/', SectionHomeTemplateListView.as_view(), name='insurance.section_home_template.list'),
	path('section-home/add/', SectionHomeTemplateAddView.as_view(), name='insurance.section_home_template.add'),
	path('section-home/<int:pk>/edit/', SectionHomeTemplateEditView.as_view(),
		 name='insurance.section_home_template.edit'),

	path('section-icon/add/', SectionIconAddView.as_view(), name='insurance.section_icon.add'),
	path('section-icon/<int:pk>/edit/', SectionIconEditView.as_view(), name='insurance.section_icon.edit'),

	# Company URL'S
	path('company/', CompanyListView.as_view(), name='insurance.company.list'),
	path('company/add/', CompanyAddView.as_view(), name='insurance.company.add'),
	path('company/<int:pk>/edit/', CompanyEditView.as_view(), name='insurance.company.edit'),

	# # Insurance Category URL'S
	# path('insurance-category/', InsuranceCategoryListView.as_view(), name='insurance.insurance_category.list'),
	# path('insurance-category/add/', InsuranceCategoryAddView.as_view(), name='insurance.insurance_category.add'),
	# path('insurance-category/<int:pk>/edit/', InsuranceCategoryEditView.as_view(),
	# 	 name='insurance.insurance_category.edit'),

	# Insurance Property URL'S
	path('insurance-property/', InsurancePropertyListView.as_view(), name='insurance.insurance_property.list'),
	path('insurance-property/add/', InsurancePropertyAddView.as_view(), name='insurance.insurance_property.add'),
	path('insurance-property/<int:pk>/edit/', InsurancePropertyEditView.as_view(),
		 name='insurance.insurance_property.edit'),
	path('insurance-property/sort/', InsurancePropertySortView.as_view(), name='insurance.insurance_property.sort'),

	# Insurance Info URL'S
	path('insurance-info/', InsuranceInfoListView.as_view(), name='insurance.insurance_info.list'),
	path('insurance-info/add/', InsuranceInfoAddView.as_view(), name='insurance.insurance_info.add'),
	path('insurance-info/<int:pk>/detail/', InsuranceInfoDetailView.as_view(),
		 name='insurance.insurance_info.detail'),
	path('insurance-info/<int:pk>/edit/', InsuranceInfoEditView.as_view(), name='insurance.insurance_info.edit'),

	path('insurance-info/<int:insurance_info_id>/add-property/', InsuranceInfoPropertyAddView.as_view(),
		 name='insurance.insurance_info.add_property'),
	path('insurance-info/<int:insurance_info_id>/add-insurance/', InsuranceAddFromInfoView.as_view(),
		 name='insurance.insurance_info.add_insurance'),

	# Insurance Info Property URL'S
	path('insurance-property-info/<int:pk>/edit/', InsuranceInfoPropertyEditView.as_view(),
		 name='insurance.insurance_info_property_edit'),
	path('insurance-property-info/<int:pk>/delete/', InsuranceInfoProperyDeleteView.as_view(),
		 name='insurance.insurance_info_property.delete'),

	# Insurance URL'S
	path('insurance/<int:pk>/edit/', InsuranceEditView.as_view(), name='insurance.insurance.edit'),


	#client info 
	path('client-info/get-counties/', GetCountyView.as_view(), name='insurance.client-info.get_models'),
	path('client-info/get-districts/', GetDistrictView.as_view(), name='insurance.client-info.get_districts'),
	path('client-info/get-barrios/', GetBarrioView.as_view(), name='insurance.client-info.get_barrios'),


	# Brand URL'S
	path('vehicle-brand/', VehicleBrandListView.as_view(), name='insurance.vehicle_brand.list'),
	path('vehicle-brand/add/', VehicleBrandAddView.as_view(), name='insurance.vehicle_brand.add'),
	path('vehicle-brand/<int:pk>/detail/', VehicleBrandDetailView.as_view(), name='insurance.vehicle_brand.detail'),
	path('vehicle-brand/<int:pk>/edit/', VehicleBrandEditView.as_view(), name='insurance.vehicle_brand.edit'),
	path('vehicle-brand/get-models/', GetModelbyBrandView.as_view(), name='insurance.vehicle_brand.get_models'),
	path('vehicle-brand/get-years/', GetYearByModel.as_view(), name='insurance.vehicle_brand.get_years'),

	path('vehicle-brand/<int:vehicle_brand_id>/add-model/', VehicleModelAddView.as_view(),
		 name='insurance.vehicle_brand.add_model'),
	path('vehicle-brand/<int:pk>/edit-model/', VehicleModelEditView.as_view(),
		 name='insurance.vehicle_brand.edit_model'),

	# Insurance Life Response URL'S
	path('insurance-life-response/', LifeResponseListView.as_view(),
		 name='insurance.insurance_life_response.list'),
	path('insurance-life-response/add/', LifeResponseAddView.as_view(),
		 name='insurance.insurance_life_response.add'),
	path('insurance-life-response/<int:pk>/edit/', LifeResponseEditView.as_view(),
		 name='insurance.insurance_life_response.edit'),

	# Insurance Vehicle Response URL'S
	path('insurance-vehicle-response/', VehicleResponseListView.as_view(),
		 name='insurance.insurance_vehicle_response.list'),
	path('insurance-vehicle-response/add/', VehicleResponseAddView.as_view(),
		 name='insurance.insurance_vehicle_response.add'),
	path('insurance-vehicle-response/<int:pk>/edit/', VehicleResponseEditView.as_view(),
		 name='insurance.insurance_vehicle_response.edit'),

	# Insurance Medical Response URL'S
	path('insurance-medical-response/', MedicalResponseListView.as_view(),
		 name='insurance.insurance_medical_response.list'),
	path('insurance-medical-response/add/', MedicalResponseAddView.as_view(),
		 name='insurance.insurance_medical_response.add'),
	path('insurance-medical-response/<int:pk>/edit/', MedicalResponseEditView.as_view(),
		 name='insurance.insurance_medical_response.edit'),
	path('insurance-medical-response/<int:medical_response_id>/add-dependent/',
		 MedicalResponseAddDependentView.as_view(), name='insurance.insurance_medical_response.add_dependent'),
	path('insurance-medical-response/<int:dependent_id>/delete-dependent/',
		 MedicalResponseDeleteDependentView.as_view(), name='insurance.insurance_medical_response.delete_dependent'),

	# Insurance Home Response URL'S
	path('insurance-home-response/', HomeResponseListView.as_view(), name='insurance.insurance_home_response.list'),
	path('insurance-home-response/add/', HomeResponseAddView.as_view(), name='insurance.insurance_home_response.add'),
	path('insurance-home-response/<int:pk>/edit/', HomeResponseEditView.as_view(),
		 name='insurance.insurance_home_response.edit'),

	# Construction Type URL'S
	path('construction-type/', ConstructionTypeListView.as_view(), name='insurance.construction_type.list'),
	path('construction-type/add/', ConstructionTypeAddView.as_view(), name='insurance.construction_type.add'),
	path('construction-type/<int:pk>/edit/', ConstructionTypeEditView.as_view(),
		 name='insurance.construction_type.edit'),

	# Feauture URL'S
	path('feature/', FeatureListView.as_view(), name='insurance.feature.list'),
	path('feature/add/', FeatureAddView.as_view(), name='insurance.feature.add'),
	path('feature/<int:pk>/edit/', FeatureEditView.as_view(), name='insurance.feature.edit'),

	# Client Response URL'S
	path('client-response/', ClientResponseListView.as_view(), name='insurance.client_response.list'),
	path('client-response/<int:pk>/detail/', ClientResponseDetail.as_view(), name='insurance.client_response.detail'),

	# Vehicle Year URL'S
	path('vehicle-year/', VehicleYearListView.as_view(), name='insurance.vehicle_year.list'),
	path('vehicle-year/add/', VehicleYearAddView.as_view(), name='insurance.vehicle_year.add'),
	path('vehicle-year/<int:pk>/edit/', VehicleYearEditView.as_view(), name='insurance.vehicle_year.edit'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insurance/models/Client.py
from django.db import models


class Client(models.Model):
	first_name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	email = models.EmailField(max_length=255, null=True, blank=True)
	phone = models.CharField(max_length=50, null=True, blank=True)

	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return '{0} {1}'.format(self.first_name.title(), self.last_name.title())

	@property
	def get_insurance_type(self):
		if self.life_responses.exists():
			return 'Vida'

		elif self.medical_responses.exists():
			return 'Médico'

		elif self.vehicle_responses.exists():
			return 'Vehículos'

		elif self.home_responses.exists():
			return 'Casas'

insurance/models/ClientHomeResponse.py
from django.db import models

from insurance.models.HomeResponseTemplate import HomeResponseTemplate


class ClientHomeResponse(HomeResponseTemplate):
	client = models.ForeignKey('insurance.Client', related_name='home_responses', on_delete=models.CASCADE)

	insurance = models.ManyToManyField('insurance.Insurance', related_name='client_home_responses')

insurance/models/ClientInfo.py
from django.db import models


class ClientInfo(models.Model):
	
	cedula = models.IntegerField(primary_key=True)
	codelect = models.IntegerField()
	sexo =  models.IntegerField()
	fechacaduc = models.IntegerField()
	junta = models.CharField(max_length=10,null=True)
	nombre = models.CharField(max_length=50,null=True)
	apellido1 = models.CharField(max_length=50,null=True)
	apellido2 = models.CharField(max_length=50,null=True)

	# def __str__(self):
	# 	return self.cedula.value()

	@classmethod
	def get_by_id(cls,client_id):
		try:
			client_info = cls.objects.get(cedula=client_id)

		except cls.DoesNotExist:
			client_info = None

		return client_info

	#@property
	#def sorted_client_models(self):
	#	return self.vehicle_models.all().order_by('name')

insurance/models/ClientLifeResponse.py
from django.db import models

from insurance.models.LifeResponseTemplate import LifeResponseTemplate


class ClientLifeResponse(LifeResponseTemplate):
	client = models.ForeignKey('insurance.Client', related_name='life_responses', on_delete=models.CASCADE)

	insurance = models.ManyToManyField('insurance.Insurance', related_name='client_life_responses')

insurance/models/ClientMedicalResponse.py
from django.db import models

from insurance.models.MedicalResponseTemplate import MedicalResponseTemplate


class ClientMedicalResponse(MedicalResponseTemplate):
	client = models.ForeignKey('insurance.Client', related_name='medical_responses', on_delete=models.CASCADE)

	insurance = models.ManyToManyField('insurance.Insurance', related_name='client_medical_responses')

insurance/models/ClientMedicalResponseDependents.py
from django.db import models

from insurance.models.MedicalResponseDependentsTemplate import MedicalResponseDependentsTemplate


class ClientMedicalResponseDependents(MedicalResponseDependentsTemplate):
	client_medical_response = models.ForeignKey('insurance.ClientMedicalResponse',
												related_name='dependents',
												on_delete=models.CASCADE)

insurance/models/ClientVehicleResponse.py
from django.db import models

from insurance.models.VehicleResponseTemplate import VehicleResponseTemplate


class ClientVehicleResponse(VehicleResponseTemplate):
	client = models.ForeignKey('insurance.Client', related_name='vehicle_responses', on_delete=models.CASCADE)

	insurance = models.ManyToManyField('insurance.Insurance', related_name='client_vehicle_responses')

insurance/models/Color.py
from django.db import models


class Color(models.Model):
	name = models.CharField(max_length=255,null=True)
	qualitas_color_code = models.CharField(max_length=255,default=None,null=True)
	ins_color_code = models.CharField(max_length=5,default=None,null=True)
	oceanica_color_code = models.CharField(max_length=255,default=None,null=True)
	created_at = models.DateTimeField(auto_now_add=True,null=True)
	updated_at = models.DateTimeField(auto_now=True,null=True)

	def __str__(self):
		return self.name.title()

	@classmethod
	def get_by_id(cls, color_id):
		try:
			color = cls.objects.get(id=color_id)

		except cls.DoesNotExist:
			color = None

		return color

	

insurance/models/Company.py
from django.db import models


class Company(models.Model):
	name = models.CharField(max_length=255)

	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name.title()

insurance/models/ConstructionType.py
from django.db import models


class ConstructionType(models.Model):
	name = models.CharField(max_length=255)

	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name.title()

insurance/models/County.py
from django.db import models


class County(models.Model):
	name = models.CharField(max_length=255,null=True)
	qualitas_county_code = models.CharField(max_length=255,default=None,null=True)
	oceanica_county_code = models.CharField(max_length=255,default=None,null=True)
	ins_county_code = models.CharField(max_length=5,default=None,null=True)
	state = models.ForeignKey('insurance.State', related_name='state_counties', on_delete=True,null=True)
	created_at = models.DateTimeField(auto_now_add=True,null=True)
	updated_at = models.DateTimeField(auto_now=True,null=True)

	def __str__(self):
		return self.name.title()

	
	@classmethod
	def get_by_id(cls, county_id):
		try:
			county = cls.objects.get(id=county_id)

		except cls.DoesNotExist:
			county = None

		return county

	@property
	def sorted_county_districts(self):
		return self.county_districts.all().order_by('name')

insurance/templates/insurance/insurance_property/insurance_property_list.html
{% extends 'insurance/layout/base.html' %}

{% block title %}
    Propiedades de Seguros
{% endblock %}

{% block breadcrumb %}
    Propiedades de Seguros
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card card-accent-primary">
                <div class="card-header">Lista de Propiedades</div>
                <div class="card-body">
                    <table class="table table-responsive-sm">
                        <thead>
                        <tr>
                            <th class="col-lg-11">Nombre</th>
                            <th class="col-lg-1"></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for insurance_property in insurance_property_list %}
                            <tr>
                                <td>{{ insurance_property }}</td>
                                <td class="text-center">
                                    <a href="{% url 'insurance.insurance_property.edit' insurance_property.id %}"
                                       class="text-warning"
                                       title="Editar">
                                        <i class="far fa-edit"></i>
                                    </a>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="2" class="text-center text-danger">
                                    <h4>No hay propiedades disponibles</h4>
                                </td>
                            </tr>
                        {% endfor %}
                        {% if company_list %}
                            {% include 'insurance/layout/paginator.html' with colspan=2 %}
                        {% endif %}
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <div class="row justify-content-lg-end">
                        <div class="col-lg-6 text-right">
                            <a href="{% url 'insurance.insurance_property.sort' %}" class="text-cyan"><i
                                    class="fas fa-sort"></i> Ordenar</a>&nbsp;
                            <a href="{% url 'insurance.insurance_property.add' %}" class="text-success">
                                <i class="far fa-file"></i> Nueva Propiedad
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

insurance/templates/insurance/insurance_property/insurance_property_sort.html
{% extends 'insurance/layout/base.html' %}

{% block title %}
    Ordernar Propiedades de Seguro
{% endblock %}

{% block breadcrumb %}
    Propiedades de Seguro
{% endblock %}

{% block content %}
    <div class="row justify-content-lg-center">
        <div class="col-lg-6">
            <div class="card card-accent-cyan">
                <div class="card-header">Ordernar Propiedades de Seguro</div>
                <div class="card-body">
                    <form id="sort_form" method="post" action="">{% csrf_token %}
                        <ul id="sort_list" class="list-group">
                            {% for insurance_property in insurance_property_list %}
                                <li id="{{ insurance_property.id }}" class="list-group-item">
                                    {{ insurance_property }}
                                </li>
                            {% endfor %}
                        </ul>
                        <br/>
                        <div class="form-group text-right">
                            <button id="btn_save_order" type="submit" class="btn btn-success">Ordenar</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-lg-6">
                            <a href="{% url 'insurance.insurance_property.list' %}"><i class="fas fa-arrow-left"></i>
                                Regresar</a>
                        </div>
                        <div class="col-lg-6"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js_scripts %}

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>
        $(function () {
            $("#sort_list").sortable().disableSelection();
        });

        $("#btn_save_order").click(function (e) {
            var array_properties = [];

            var sort_form = $("#sort_form");

            $("#sort_list li").each(function () {
                array_properties.push($(this).attr('id'));
            });

            sort_form.append('<input type="hidden" id="insurance_property_ids" name="insurance_property_ids" value="' + array_properties + '">');

            sort_form.submit();

            e.preventDefault();
        });

    </script>

{% endblock %}